### ISSUE TITLE
Bug in python client/bindings for elasticsearch pip package

### ISSUE THREAD

**Issue by djui** [elasticsearch/puppet-elasticsearch#145]
When trying to use the `elasticsearch` pip package I get:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Cannot alias Package[python_elasticsearch] to ["elasticsearch"] at /modules/foo/manifests/init.pp:87; resource ["Package", "elasticsearch"] already declared at /modules/elasticsearch/manifests/package.pp:171 at /modules/foo/manifests/init.pp:87 on node localhost
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I think the last fix bda8bc2234d32788f75c679f153876133f00d871 did not help.

**Comment by electrical** [comment]
I've been digging into this issue a bit more and there seems to be no decent solution.
There is however a ticket at PuppetLabs to fix this issue in Puppet 4.x ( https://tickets.puppetlabs.com/browse/PUP-1073 )

**Comment by electrical** [comment]
I'm afraid that until that is solved this will remain an issue with all previous puppet versions.
