### ISSUE TITLE
Modifications to the module we can make

### ISSUE THREAD

**Issue by electrical** [elasticsearch/puppet-elasticsearch#150]
Hi all,

Now Puppet pre 3.2 support is dropped ( see this [blog](http://www.elasticsearch.org/blog/streamlining-maintenance-puppet-modules/) ) i wonder what cool improvements we can make to the module.

Input and PR's are very welcome.

**Comment by electrical** [comment]
Hiera support is almost done via PR https://github.com/elasticsearch/puppet-elasticsearch/pull/179

@erik-stephens i'm currently looking at your proposed change and see it makes sense to implement it.

**Comment by erik-stephens** [comment]
@electrical Maybe just `$instances` and ditch x_instances?  I *think* will be more idiomatic puppet.  Assuming only need to support puppet >= 3, then elasticsearch::instances will be automatically looked up and applied to that variable.  That's how I'm currently using your module now and works perfect for me.  I wrote my comment before knowing about automatic parameter lookup.  I don't see the need to support a merge of hiera-defined instances with explicitly defined ones - I expect people will be doing it one way or the other.

**Comment by electrical** [comment]
The `hiera_hash` function allows to merge instances from multiple hiera files that may be present in the lookup.
For example one could have a default instance ( data instance ) for all nodes and some of them have a separate master instance next to it.
These 2 instances could then be configured into 2 separate hiera files.
I'm not sure if they would want to happen automatically?

**Comment by erik-stephens** [comment]
Ah, I forgot that automatic param lookup is priority only, not merged.  Feel free to ignore my original comment - it was an attempt to help make it a bit simpler.

**Comment by electrical** [comment]
@erik-stephens no worries. I appreciate all input and idea's :-)

**Comment by electrical** [comment]
Hi all,

I'm going to close this issue as most or all improvements have been implemented and will be released soon.
I'll open a new one at some point to look forward towards Puppet 4.0 and what we can do there.
Thank you very much for the involvement!
