### ISSUE TITLE
instance won't start on Ubuntu 14.04

### ISSUE THREAD

**Issue by lsh-0** [elasticsearch/puppet-elasticsearch#182]
I'm running a box attempting to configure elasticsearch, kibana and logstash.

I'm trying to determine if the elasticsearch instance is running, but it doesn't appear to be:

    vagrant@env1:~$ sudo service elasticsearch status
     * elasticsearch is not running
    vagrant@env1:~$ sudo service elasticsearch start
     * Starting Elasticsearch Server                                                             [ OK ] 
    vagrant@env1:~$ sudo service elasticsearch status
     * elasticsearch is not running

and

    vagrant@env1:~$ sudo /etc/init.d/elasticsearch status
     * elasticsearch is not running
    vagrant@env1:~$ sudo /etc/init.d/elasticsearch start
     * Starting Elasticsearch Server                                                             [ OK ] 
    vagrant@env1:~$ sudo /etc/init.d/elasticsearch status
     * elasticsearch is not running

and

    vagrant@env1:~$ curl -XGET localhost:9200/_nodes/_all/process?pretty
    curl: (7) Failed to connect to localhost port 9200: Connection refused

firewall rules:

    vagrant@env1:~$ sudo iptables --list
    Chain INPUT (policy ACCEPT)
    target     prot opt source               destination         

    Chain FORWARD (policy ACCEPT)
    target     prot opt source               destination         

    Chain OUTPUT (policy ACCEPT)
    target     prot opt source               destination    

my configuration is:

    class { 'elasticsearch': 
        package_url => 'https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.3.2.deb',
    }

    elasticsearch::instance { 'es-01': }

and this doesn't work either:

    vagrant@env1:~$ sudo /etc/init.d/elasticsearch-es-01 status
     * elasticsearch is not running
    vagrant@env1:~$ sudo /etc/init.d/elasticsearch-es-01 start
     * Starting Elasticsearch Server es-01                                        [ OK ] 
    vagrant@env1:~$ sudo /etc/init.d/elasticsearch-es-01 status
     * elasticsearch is not running

I'm new to Elasticsearch, puppet and this module and this is getting quite frustrating. Do you have any insight into what the problem might be or how I've managed to misconfigure your module?

**Comment by yasirbam** [comment]
I am having the same issue after deciding to restart elasticsearch that has been running for a couple of months! now I am not able to start it. 
the start up service silently prints OK, when I run Sudo service elasticsearch start, but nothing in the logs
something must have upgraded while ES was running!

**Comment by bendiu** [comment]
Try /etc/init.d/elasticsearch start

**Comment by lrafagnin** [comment]
I had a similar issue, selinux was blocking it from running on the background
You can test this by running on the foreground, should work ./elasticsearch -f 
Next step is checking /var/log/secure

**Comment by alyssondaniel** [comment]
Ubuntu 15.04

$ /usr/share/elasticsearch/bin/elasticsearch

out: AccessDeniedException[/usr/share/elasticsearch/data]

$ sudo mkdir /usr/share/elasticsearch/data

$ sudo chown elasticsearch.elasticsearch /usr/share/elasticsearch/data -R

**Comment by electrical** [comment]
@alyssondaniel please create a new issue and give a bit more details like which version of the module you are using and your puppet parts.

**Comment by alyssondaniel** [comment]
ok

**Comment by jeanleonov** [comment]
I also experienced this issue on Ubuntu 12.04.
In my case **the problem was related to user rights**. When I start ES using `/usr/share/elasticsearch/bin/elasticsearch` it runs with privileges of my user. But script `/etc/init.d/elasticsearch` runs it as elasticsearch user which in my case hadn't rights to data folder.
**To find it out I ran**
`sudo start-stop-daemon --start --user elasticsearch -c elasticsearch --pidfile /var/run/elasticsearch.pid --exec /usr/share/elasticsearch/bin/elasticsearch -- -d -p /var/run/elasticsearch.pid --default.config=/etc/elasticsearch/elasticsearch.yml --default.path.home=/usr/share/elasticsearch --default.path.logs=/var/log/elasticsearch --default.path.data=/var/lib/elasticsearch --default.path.work=/tmp/elasticsearch --default.path.conf=/etc/elasticsearch`
**without -b argument** (not in background) and it printed stacktrace about error.

**Comment by J-Zet** [comment]
Had the same problem, in my case JAVA wasnt able to allocate enough memory for itself.
