### ISSUE TITLE
elasticsearch::instance doesn't handle conflicting parameters

### ISSUE THREAD

**Issue by mfournier** [elasticsearch/puppet-elasticsearch#186]
The following code snippet doesn't fail, but randomly switches ES datadir from `/foo` to `/bar` and back :
```
elasticsearch::instance { 'auth-logs':
  datadir    => '/foo',
  config     => {
    'path'   => {
      'data' => '/bar',
    },
  },
}
```

I believe it should either fail or discard one of the 2.

**Comment by electrical** [comment]
@mfournier finally had the time to build a fix for this including some tests.
Will be fixed with the next release. sorry it took so long.

**Comment by electrical** [comment]
This should be fixed now. you can try out the master repo or wait for a release.
again, thank you for reporting it.
