### ISSUE TITLE
Error: false is not a string. when repo_version is not set

### ISSUE THREAD

**Issue by mmarseglia** [elasticsearch/puppet-elasticsearch#189]
repo_version is initialized to false.
 $manage_repo           = false,
  $repo_version          = false,
  $logging_file          = undef,

init.pp line 258 tests if repo_version is a string
  if ($manage_repo == true) {
    validate_string($repo_version)
  }

if repo_version is not set then puppet reports error: Error: false is not a string.  It looks to be a FalseClass at elasticsearch/manifests/init.pp:258

I was confused when I saw the error message at first. shouldn't repo_version be set to undef or empty string?

**Comment by electrical** [comment]
With https://github.com/elasticsearch/puppet-elasticsearch/pull/252 I've added a more human friendly error message.
