### ISSUE TITLE
Need mechanism for managing maxBackupIndex for the dailyRollingFile logs in logging.yml

### ISSUE THREAD

**Issue by shanemadden** [elasticsearch/puppet-elasticsearch#193]
Let me know if I'm missing something here, but it doesn't look like there's any way to manage the `maxBackupIndex` attribute for the files set in the `logging.yml` - it doesn't seem like there's any mechanism for setting that via the logging config hash, since it needs to be defined in the blocks for the individual files?

I've accomplished this in our local version of the module by adding a `$logging_days` param to the base class and using that in the `logging.yml` template, let me know if that solution sounds reasonable and I'll put it in a PR.

**Comment by electrical** [comment]
Hi,

A feature has been added so you can create your own logging.yml template.
You can also use a plain logging.yml file.
the logging_config hash should be improved indeed but is not on my todo list at the moment.

Cheers.
