### ISSUE TITLE
Setting statuses on individual ElasticSearch instances

### ISSUE THREAD

**Issue by reamer77** [elasticsearch/puppet-elasticsearch#199]
I have a master instance and a data instance.  I'd like the master instance to start on boot, and the data instance to be started later (preferably by a cluster management script).  I was trying 

  elasticsearch::instance { 'es-master':
    status => 'enabled'
  }

  elasticsearch::instance { 'es-0':
    status => 'running'
  }

However, it looks like the "status" value set in ::elasticsearch does not get overridden by the instance values.  Not specifying a "status" value in ::elasticsearch seems to default to "enabled".  Is it possible to set unique statuses per instance?

Thanks!

**Comment by electrical** [comment]
Hi,

I've done a test by setting the status to `enabled` on the main class and to `running` and then evaluated the actual settings for the service and it appears to work as expected.
It sets the service to running but without enabling it.

**Comment by reamer77** [comment]
OK thanks!
