### ISSUE TITLE
/var/run/elasticsearch folder isn't chown'd

### ISSUE THREAD

**Issue by chriswhite199** [elasticsearch/puppet-elasticsearch#206]
When configuring a different es user / group through the elasticsearch_user and elasticsearch_group params, the pid folder isn't chown'd to the new user:group, which prevents the instance from starting as a service.

### Config:

    class { 'elasticsearch':
      package_url => 'puppet:///modules/elasticsearch/elasticsearch-1.1.1.noarch.rpm',
      config => {
        'node' => {
          'name' => $::fqdn
        },
        'index'                => {
            'number_of_replicas' => '1',
            'number_of_shards'   => '5'
          },
          'network'              => {
            'host'               => $::ipaddress
          },
          'cluster'              => {
            'name'               => "esearch",
          }
      },
      elasticsearch_user => 'elastics',
      elasticsearch_group => 'elastics',
    }

    elasticsearch::instance { 'es-01': }

### Starting instance:

    Starting elasticsearch-es-01:                              [  OK  ]
    [root@2c9efb74cbb1 manifests]# {1.1.1}: pid Failed ...
    - FileNotFoundException[/var/run/elasticsearch/elasticsearch-es-01.pid (Permission denied)]

### Directory listing:

    [root@2c9efb74cbb1 puppet]# ll /var/run/elasticsearch -a
    total 8
    drwxr-xr-x. 2 elasticsearch elasticsearch 4096 Apr 16  2014 .
    drwxr-xr-x. 9 root          root          4096 Dec 12 03:44 ..

**Comment by electrical** [comment]
Hi,

I've just merged a fix into the master branch which should solve the rights issues.

Cheers.

**Comment by electrical** [comment]
Testing showed this issue to be fixed in the master branch.
Closing the issue for now, could you open a new one if its not fixed? Thanks!
