### ISSUE TITLE
Set Open File Limit

### ISSUE THREAD

**Issue by TJM** [elasticsearch/puppet-elasticsearch#223]
According to GrayLog2: https://www.graylog2.org/resources/documentation/setup/elasticsearch
... and elastic search docs: http://www.elasticsearch.org/tutorials/too-many-open-files/

The number of open files should be raised for elasticsearch. The module should take care of that by default if its required for operation.

EDIT: on RedHat based OS, it does appear to have that default of 65536 on OpenSuSE and Debian

**Comment by electrical** [comment]
Hi,

With Elasticsearch we handle this in the init scripts like [here](https://github.com/elasticsearch/elasticsearch/blob/master/src/rpm/init.d/elasticsearch#L74-L76) which can be set via the init_defaults hash.
Hope this clarifies it for you?

**Comment by TJM** [comment]
I agree that it is customizable via the init_defaults hash, and I *do* appreciate that. My point was that it is the default for:

* Debian: https://github.com/elasticsearch/puppet-elasticsearch/blob/master/templates/etc/init.d/elasticsearch.Debian.erb#L73
* SuSE: https://github.com/elasticsearch/puppet-elasticsearch/blob/master/templates/etc/init.d/elasticsearch.OpenSuSE.erb#L13

But not for RHEL/CentOS: https://github.com/elasticsearch/puppet-elasticsearch/blob/master/templates/etc/init.d/elasticsearch.RedHat.erb#L73-L75

... and I think it should be :)

~tommy

**Comment by electrical** [comment]
Good point, I'll see if i can improve on it.

**Comment by TJM** [comment]
Thank you, sir!

**Comment by electrical** [comment]
@TJM i have the following in mind to solve this.
I can set a default value in the Puppet module to 65k which gets put into the defaults file but can be overwritten by the init_defaults hash when more then 65k is required.
Does that sound okay to you?

**Comment by TJM** [comment]
Yea, I think that is inline with what the other OS's mentioned above are doing.

**Comment by electrical** [comment]
Solved with https://github.com/elasticsearch/puppet-elasticsearch/pull/250
