### ISSUE TITLE
puppet sets binary /usr/share/elasticsearch/bin/elasticsearch to mode 0644

### ISSUE THREAD

**Issue by mmarseglia** [elasticsearch/puppet-elasticsearch#242]
Hi,

  We're using latest and it appears puppet sets the binary /usr/share/elasticsearch/bin/elasticsearch to mode 0644.

  In the elasticsearch init script
`exec="/usr/share/elasticsearch/bin/elasticsearch"`

  Further down the init script checks to see if exec is executable and if not, fails.
`start() {
    checkJava
    [ -x $exec ] || exit 5`

  When I change the file mode myself, I see puppet module Elasticsearch::Config changing it to 0644 when I run the agent in debug mode:
> Notice: /Stage[main]/Elasticsearch::Config/File[/usr/share/elasticsearch/bin/elasticsearch]/mode: current_value 0755, should be 0644 (noop)

**Comment by electrical** [comment]
Hi is this with the latest release or master brarch ?

**Comment by mmarseglia** [comment]
master

**Comment by electrical** [comment]
Strange my acceptance runs never failed.
I'll double check it on my end and if needed I'll add something to force the bin dir to 755.

Thanks for reporting this.

**Comment by mmarseglia** [comment]
We installed elasticsearch version 0.90.13.  Would that make a difference?

**Comment by electrical** [comment]
Don't think it should. I may have overlooked something. I'll check tomorrow and reply back on the issue.

**Comment by electrical** [comment]
Hi, could you re-check master?
I'm not setting the mode explicitly.
Of course i could force the bin dir files to be 755 but i don't see the same log in my tests.

**Comment by CharlieR-o-o-t** [comment]
I think that problem comes here 
config.pp
```
    file { $elasticsearch::datadir:
      ensure  => 'directory',
      recurse => true
    }
```
It's better to set right explicitly. Because, if we have something like this at our manifest
```
  File{
    mode          => '0644',
  }
```
Rights will be overridden and elasticsearch will fail to start. It's critical to have X bit here.

**Comment by electrical** [comment]
Ahh okay, now i understand where it comes from.
I'll see if i can make sure the bin directory files will be forced to 755

**Comment by CharlieR-o-o-t** [comment]
sorry, it's critical for me. 
I have submitted pull request, could you look ? 
https://github.com/elasticsearch/puppet-elasticsearch/pull/244

**Comment by electrical** [comment]
I've just merged a PR that fixes this issue. can you validate?
