### ISSUE TITLE
elastic search instance creation

### ISSUE THREAD

**Issue by eljohn1014** [elasticsearch/puppet-elasticsearch#246]
I am trying to create a elastic search instance called es-01, when it is created I have 2 services running, one with cluster name "elasticsearch" and another with the correct name, the "elasticsearch" cluster does not have the right configurations so it is not working. in order to fix this I have manually kill the incorrect process and restarted the elasticsearch-es-01 process to get it to pick up the right config. is there a setting i could be missing where it creates a default instance on elastic search install?

**Comment by electrical** [comment]
Hi,

There should be no default instance since that would be weird magical stuff happening that users don't expect.
However the original init script does still exist after the package installation.
In the master branch I already fixed this by simply removing the original package files to avoid confusion.
Does this answer you question?

**Comment by eljohn1014** [comment]
I don't have it pinned to any specific version so it should be grabbing the latest, in the init.d folder I am only seeing elasticsearch-es-01, but when I look at the processes I see two processes running, one with default config path in /etc/elasticsearch and one in /etc/elasticsearch/es-01 (where the config actually is) is there a place this first one could be coming from besides the elasticsearch::instance call?

**Comment by electrical** [comment]
Can you tell me which ES version you are installing? I can remember there were versions that would automatically start ES at installation time.

**Comment by eljohn1014** [comment]
we are using 0.90.13-1

**Comment by eljohn1014** [comment]
we are also calling class{'::elasticsearch' :...} and ::elasticsearch::instance { 'es-01' :...}, should only one of these be called?

**Comment by electrical** [comment]
Ah. 0.90 versions indeed started the init script after installation. that's why you have 2 instances running.
You're puppet code is fine, you indeed need the main class and the instance define.
I think its best to upgrade to 1.4.x :-)

**Comment by eljohn1014** [comment]
we are unfortunately pinned to 9.0 will we have to just manually turn it off then?

**Comment by electrical** [comment]
I'm afraid so yeah. since we delete the init file inside the module you can't do a service call anymore to disable it.

**Comment by eljohn1014** [comment]
Is there a setting we can set on the original class or instance such as turning it off right away or changing the port so that there wont be any problems with this?

**Comment by electrical** [comment]
With the new release that's coming we remove the files and assume its not started by default. ( the 'elasticsearch' one )
This puppet module assumes you have 1.0 or up.

0.90.x is also EOL.
