### ISSUE TITLE
instance settings do not override class settings

### ISSUE THREAD

**Issue by gingaz** [elasticsearch/puppet-elasticsearch#248]
Hi Everyone,

the following example creates two disabled elasticsearch services. However, I would like to have "test-elasticsearch' running and 'elasticsearch' - stopped.
```
class { 'elasticsearch':
  status       => 'disabled',
}
elasticsearch::instance { 'test-elasticsearch':
  status => 'enabled',
}
```

The workaround is:
```
class { 'elasticsearch':
  status       => 'disabled',
}->
elasticsearch::instance { 'test-elasticsearch':
  status => 'enabled',
}->
service{ 'elasticsearch':
status => disabled',
}
```
Cheers,
Gin

**Comment by electrical** [comment]
Hi,

The 'elasticsearch' instance will be removed in the next release and not managed.
if you use 0.90.x I'm afraid there is no nice solution since 0.90.x packages automatically start up ES after installation.

**Comment by gingaz** [comment]
Thanks for clarifying.
