### ISSUE TITLE
config parameter works only for instance types, but not the class

### ISSUE THREAD

**Issue by gingaz** [elasticsearch/puppet-elasticsearch#249]
Hi,

This does nothing:
```
class { 'elasticsearch':
  ... other settings
  config => {'http.cors.enabled' => 'true'},
}
```

Whereas this works
```
elasticsearch::instance { 'test-elasticsearch':
  config => {'http.cors.enabled' => 'true'},
}
```

Can you please confirm this?
That is the only reason why I am using es instances - to put settings into effect.

Thanks,
Gin

**Comment by electrical** [comment]
Hi,

Since the module supports multiple instances its mandatory to define atleast one.
Please see https://github.com/elasticsearch/puppet-elasticsearch#instances for more information.

**Comment by gingaz** [comment]
I thought I can set "global" elasticsearch configuration in the class and then make it fine grain in instances.

Thanks.

**Comment by electrical** [comment]
Hi,
The config variable from the main class should be passed on to the instances functions indeed.
You will still need to define an instance though.

**Comment by gingaz** [comment]
Go it. Thanks :)
