### ISSUE TITLE
ES_HEAP_SIZE should have an override / be a variable in the initscript erb.

### ISSUE THREAD

**Issue by derjohn** [elasticsearch/puppet-elasticsearch#262]
Currently there is no way to give the ES more than 1G HEAP. There is no placeholder in the init script.

**Comment by electrical** [comment]
Hi,

You can define the ES_HEAP_SIZE in the defaults file which gets exported by the init script and then picked up by ES it self.

**Comment by derjohn** [comment]
Thx!

**Comment by gbirke** [comment]
I had the same problem and was very close to opening another issue for it. Maybe you can add ES_HEAP_SIZE to the defaults example in the readme?

**Comment by electrical** [comment]
@gbirke good idea, will do that for next release. thanks!
