### ISSUE TITLE
Hiera query for multiple datadirs generates incorrect mkdir command

### ISSUE THREAD

**Issue by kjhosein** [elasticsearch/puppet-elasticsearch#266]
Hello - I'm trying to add multiple datadirs into an `elasticsearch::instance {}` by pulling in an array from Hiera like this:

`es.pp`:
```
    $_es_datadirs          = hiera('es_datadirs')
    elasticsearch::instance { "esnode1":
        ensure        => present,
        datadir       => "$_es_datadirs",
        status        => 'enabled',
      }
```
And in Hiera, I have:

    es_datadirs:
      - /data/elasticsearch/disk1
      - /data/elasticsearch/disk2

However, this throws an error: `creates must be a fully qualified path`. When I dig into the catalog that's generated on the agent machine, I see the following JSON:

```
{
"line": 173,
"title": "mkdir_datadir_elasticsearch_esnode1",
"parameters": {
  "cwd": "/",
  "before": "Elasticsearch::Service[esnode1]",
  "creates": "[/data/elasticsearch/disk1, /data/elasticsearch/disk2]",
  "command": "mkdir -p [/data/elasticsearch/disk1, /data/elasticsearch/disk2]",
  "require": "Class[Elasticsearch::Package]",
  "path": [
    "/bin",
    "/usr/bin",
    "/usr/local/bin"
  ]
},
```
I could be wrong, but it appears that the generated `mkdir` command isn't formatted correctly. Or is my Hiera structure and/or query incorrect or impossible?

**Comment by electrical** [comment]
Hmm, good question, i haven't tried it in this way yet to be very honest.
Not sure if it would make a difference but you could try to use `hiera_array` ?

**Comment by electrical** [comment]
With the hiera tests that i can do i use the auto binding and that seems to work fine.
I haven't been able to try out the `hiera` call it self as rspec-puppet doesn't allow it nor have i been able to reproduce it further.
You can ignore my comment about `hiera_array` as the functionality is different then I initially though.

**Comment by philipwigg** [comment]
```datadir       => "$_es_datadirs",```

I think by quoting ```$_es_datadirs``` you are implicitly converting it to a string which might be where you're going wrong.

Try taking out the quotes?

**Comment by electrical** [comment]
@philipwigg good catch, that will most likely be the culprit. It indeed forces it to be a string if i remember correctly.

**Comment by kjhosein** [comment]
@philipwigg - that worked! Thank you both.

**Comment by electrical** [comment]
@kjhosein glad to hear it worked!
